// console.log('object');

//  $(function() 
//  {
//     $('.UserName').blur(function()
//     {
//          if($(this).val().length < 4 )
//          {
//            //$(this).parent().find('.coustom-alert').fadeIn();

//              $(this).parent().find(".coustom-alert1").fadeIn(100);

               
             

//           // $(this).css('border','1px solid red');
//          }
//          else
//          {  
//             //  $(this).parent().find('.coustom-alert').hide();
//             // $(this).css('border','1px solid green');
//          }
//     }); 
//  });